# Changes here will be overwritten by Copier
_commit: 07b1c36
_src_path: .
copyright_year: '2024'
documentation: true
email: ''
full_name: Alexandru Maxiniuc
github_username: cuinixam
open_source_license: MIT
package_name: jarvis
project_name: jarvis
project_short_description: My personal page.
project_slug: jarvis

