pipeline:
  - step: CreateVEnv
    module: pypeline.steps.create_venv
    config:
      package_manager: uv>=0.6
      python_version: 3.13
  - step: GenerateEnvSetupScript
    module: pypeline.steps.env_setup_script
  - step: PreCommit
    run: pre-commit run --all-files
  - step: PyTest
    run: pytest
  - step: BuildDocs
    run: sphinx-build -E -a docs build/docs
